name: build

on:
  workflow_call:
    secrets:
      USER_AUTH:
        required: true

jobs:
  build:
    runs-on: prox-1
    steps:
      - name: Clear .next cache
        env:
          SUDO_PASSWORD: ${{ secrets.USER_AUTH }}
        run: echo "$SUDO_PASSWORD" | sudo -S rm -rf $GITHUB_WORKSPACE/.next

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
