name: main

on:
  push:
    branches:
      - teaser-2026
  workflow_dispatch:
    inputs:
      ref:
        description: Branch or tag to build and deploy
        required: false
        default: teaser-2026
        type: string

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      ref: ${{ github.event.inputs.ref || github.ref_name }}
    secrets:
      USER_AUTH: ${{ secrets.USER_AUTH }}

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    secrets:
      USER_AUTH: ${{ secrets.USER_AUTH }}
